#!/bin/bash
# install from aur

packages="$@"

[ -z "$packages" ] && exit 0
[ $USER = "root" ] && sudo="" || sudo="sudo -s"

function finish { $sudo rm -rf /tmp/aurinstall ; }
trap finish EXIT

for package in $packages
do 
  if [ ! -d "/tmp/aurinstall/$package" ]; then
    sudo -u nobody git --no-pager clone --depth 1 https://aur.archlinux.org/$package.git /tmp/aurinstall/$package 2>&0
    [[ $? != 0 ]] && exit
  fi
  if [ -f "/usr/local/etc/aurinstall/$package.patch" ]; then
    patch --directory="/tmp/aurinstall/$package" --forward --strip=1 --input="/usr/local/etc/aurinstall/$package.patch"
  fi
  (cd "/tmp/aurinstall/$package"; sudo HOME=/tmp/aurinstall/$package -u nobody makepkg --ignorearch)
  for package in /tmp/aurinstall/$package/*.pkg.*
  do 
    $sudo pacman -U --noconfirm $package
  done
done

exit 0



