#!/bin/bash
# install from aur

packages="$@"
patchpath=$(dirname $0)"/../etc/aurinstall"

[ -z "$packages" ] && exit 0
[ $USER = "root" ] && sudo="" || sudo="sudo -s"

function finish { $sudo rm -rf /tmp/aurinstall ; }
trap finish EXIT

sudo -u nobody mkdir /tmp/aurinstall

for package in $packages
do 
  if [ ! -d "/tmp/aurinstall/$package" ]; then
    (cd "/tmp/aurinstall/"; sudo ASPROOT=/tmp/aurinstall ASPCACHE=/tmp/aurinstall -u nobody asp export $package)
    if [[ $? != 0 ]]; then
      sudo -u nobody git --no-pager clone --depth 1 https://aur.archlinux.org/$package.git /tmp/aurinstall/$package 2>&0
      [[ $? != 0 ]] && exit
    fi
  fi
  if [ -f "$patchpath/$package.patch" ]; then
    $sudo cp $patchpath/$package-* "/tmp/aurinstall/$package/"
    cat "$patchpath/$package.patch" | sudo -u nobody patch --directory="/tmp/aurinstall/$package" --forward --strip=1
  fi
  (cd "/tmp/aurinstall/$package"; sudo HOME=/tmp/aurinstall/$package -u nobody makepkg --ignorearch)
  for package in /tmp/aurinstall/$package/*.pkg.*
  do 
    $sudo pacman -U --noconfirm $package
  done
done

exit 0



